export const CARD_TYPE_UNKNOWN = 0;
export const CARD_TYPE_RESOURCE = 1;
export const CARD_TYPE_MAP = 2;
export const CARD_TYPE_MERCENARY = 3;


export const CARD_SUBTYPE_UNKNOWN = 0;

export const CARD_SUBTYPE_RESOURCE_SCRAP = 1;
export const CARD_SUBTYPE_RESOURCE_RECLAIMED = 2;
export const CARD_SUBTYPE_RESOURCE_REFINED = 3;
export const CARD_SUBTYPE_RESOURCE_AUSTRALIUM = 4;
export const CARD_SUBTYPE_RESOURCE_GRAVEL = 5;

export const CARD_SUBTYPE_MAP_2FORT = 1;

export const CARD_SUBTYPE_MERCENARY_ = 1;
